#!/bin/bash 
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DESC="Enable GPIO for the Garage Door Module"
NAME="garage-door-gpio"
SCRIPTNAME=/etc/init.d/$NAME

. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Enabling garage GPIO"
	success=0
	if [ ! -e /sys/class/gpio/gpio18 ] ; then
		echo 18 > /sys/class/gpio/export
		success=$?
		echo out > /sys/class/gpio/gpio18/direction
	fi 
        log_end_msg $success
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start}" >&2
        exit 1
        ;;
esac

exit 0
